-- ====================================================================
-- BACKUP DE TABLAS ISSFA - Fecha: 20260424
-- ====================================================================

-- Backup ITEMS_ISSFA_DETALLE
CREATE TABLE SIS.BKP_ITEMS_ISSFA_DETALLE_20260424 AS
SELECT * FROM SIS.ITEMS_ISSFA_DETALLE;

-- Backup EQUIVALENCIAS_ITEMS_ISSFA
CREATE TABLE SIS.BKP_EQUIVALENCIAS_ITEMS_ISSFA_20260424 AS
SELECT * FROM SIS.EQUIVALENCIAS_ITEMS_ISSFA;

-- Validación
SELECT 'DETALLE' as TABLA, COUNT(*) as TOTAL FROM SIS.ITEMS_ISSFA_DETALLE
UNION ALL
SELECT 'BKP_DETALLE', COUNT(*) FROM SIS.BKP_ITEMS_ISSFA_DETALLE_20260424
UNION ALL
SELECT 'EQUIVALENCIAS', COUNT(*) FROM SIS.EQUIVALENCIAS_ITEMS_ISSFA
UNION ALL
SELECT 'BKP_EQUIV', COUNT(*) FROM SIS.BKP_EQUIVALENCIAS_ITEMS_ISSFA_20260424;

-- ====================================================================
-- SCRIPT DE PÁNICO - Solo ejecutar si algo salió mal
-- ====================================================================
/*
DELETE FROM SIS.EQUIVALENCIAS_ITEMS_ISSFA;
INSERT INTO SIS.EQUIVALENCIAS_ITEMS_ISSFA SELECT * FROM SIS.BKP_EQUIVALENCIAS_ITEMS_ISSFA_20260424;

DELETE FROM SIS.ITEMS_ISSFA_DETALLE;
INSERT INTO SIS.ITEMS_ISSFA_DETALLE SELECT * FROM SIS.BKP_ITEMS_ISSFA_DETALLE_20260424;

COMMIT;
*/
